# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jjosephi <jjosephi@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/28 16:37:34 by jjosephi          #+#    #+#              #
#    Updated: 2019/07/28 22:00:10 by jjosephi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #


all :
	gcc -o colle-2 -Wall -Wextra -Werror main.c rush_check.c str_helper.c rush00.c rush01.c rush02.c rush03.c rush04.c ft_putchar.c

clean :
	/bin/rm -f *.o
	
fclean :clean
	/bin/rm -rf colle-2
	
