# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jjosephi <jjosephi@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/07/22 15:31:56 by jjosephi          #+#    #+#              #
#    Updated: 2019/07/25 22:19:12 by jjosephi         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FLAGS = -Wall -Wextra -Werror

all :
	gcc -o ft_cat $(FLAGS) *.c

clean :
	/bin/rm -f *.o

fclean : clean
	/bin/rm -rf ft_display_file